# Generation of Kubernetes YAML is still under development!
#
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.1.2
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-05-23T19:16:18Z"
  labels:
    app: tikv
  name: tikv
spec:
  containers:
  - args:
    - --addr=0.0.0.0:20160
    - --advertise-addr=localhost:20160
    - --data-dir=/data/tikv1
    - --pd=localhost:2379
    command:
    - /tikv-server
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: container
      value: podman
    - name: LANG
      value: C.UTF-8
    - name: TZ
      value: /etc/localtime
    - name: TZDIR
      value: /usr/share/zoneinfo
    image: docker.io/pingcap/tikv:latest
    name: tikv1
    ports:
    - containerPort: 2379
      hostPort: 2379
      protocol: TCP
    - containerPort: 2380
      hostPort: 2380
      protocol: TCP
    - containerPort: 20160
      hostPort: 20160
      protocol: TCP
    - containerPort: 20161
      hostPort: 20161
      protocol: TCP
    - containerPort: 20162
      hostPort: 20162
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    volumeMounts:
    - mountPath: /etc/localtime
      name: etc-localtime-host
      readOnly: true
    - mountPath: /data:z
      name: home-rustysysdev-.tikv-data-host
    workingDir: /
  - args:
    - --name=pd1
    - --data-dir=/data/pd1
    - --client-urls=http://0.0.0.0:2379
    - --advertise-client-urls=http://localhost:2379
    - --peer-urls=http://0.0.0.0:2380
    - --advertise-peer-urls=http://localhost:2380
    - --initial-cluster=pd1=http://localhost:2380
    command:
    - /pd-server
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: container
      value: podman
    - name: LANG
      value: C.UTF-8
    - name: TZ
      value: UTC
    image: docker.io/pingcap/pd:latest
    name: pd1
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    volumeMounts:
    - mountPath: /etc/localtime
      name: etc-localtime-host
      readOnly: true
    - mountPath: /data:z
      name: home-rustysysdev-.tikv-data-host
    workingDir: /
  - args:
    - --addr=0.0.0.0:20161
    - --advertise-addr=localhost:20161
    - --data-dir=/data/tikv2
    - --pd=localhost:2379
    command:
    - /tikv-server
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: container
      value: podman
    - name: TZDIR
      value: /usr/share/zoneinfo
    - name: LANG
      value: C.UTF-8
    - name: TZ
      value: /etc/localtime
    image: docker.io/pingcap/tikv:latest
    name: tikv2
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    volumeMounts:
    - mountPath: /etc/localtime
      name: etc-localtime-host
      readOnly: true
    - mountPath: /data:z
      name: home-rustysysdev-.tikv-data-host
    workingDir: /
  - args:
    - --addr=0.0.0.0:20162
    - --advertise-addr=localhost:20162
    - --data-dir=/data/tikv3
    - --pd=localhost:2379
    command:
    - /tikv-server
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: container
      value: podman
    - name: LANG
      value: C.UTF-8
    - name: TZ
      value: /etc/localtime
    - name: TZDIR
      value: /usr/share/zoneinfo
    image: docker.io/pingcap/tikv:latest
    name: tikv3
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    volumeMounts:
    - mountPath: /data:z
      name: home-rustysysdev-.tikv-data-host
    - mountPath: /etc/localtime
      name: etc-localtime-host
      readOnly: true
    workingDir: /
  dnsConfig: {}
  restartPolicy: Never
  volumes:
  - hostPath:
      path: /etc/localtime
      type: File
    name: etc-localtime-host
  - hostPath:
      path: /home/rustysysdev/.tikv/data
      type: Directory
    name: home-rustysysdev-.tikv-data-host
status: {}

